version: 2

before:
  hooks:
    - go mod download

builds:
  - id: goproxy
    main: ./cmd/goproxy
    binary: bin/goproxy
    ldflags:
      - -s -w -X github.com/goproxy/goproxy/cmd/goproxy/internal.Version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
      - linux_ppc64le
      - linux_s390x
      - windows_386
      - windows_amd64
      - windows_arm64
    mod_timestamp: "{{.CommitTimestamp}}"

dockers:
  - goarch: "386"
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-386
    use: buildx
    build_flag_templates:
      - --platform=linux/386
      - --build-arg=USE_GORELEASER_ARTIFACTS=1
      - --build-arg=GORELEASER_ARTIFACTS_TARBALL=./dist/{{.ProjectName}}_{{.Version}}_linux_386.tar.gz
    extra_files:
      - ./
  - goarch: amd64
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --build-arg=USE_GORELEASER_ARTIFACTS=1
      - --build-arg=GORELEASER_ARTIFACTS_TARBALL=./dist/{{.ProjectName}}_{{.Version}}_linux_amd64.tar.gz
    extra_files:
      - ./
  - goarch: arm64
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --build-arg=USE_GORELEASER_ARTIFACTS=1
      - --build-arg=GORELEASER_ARTIFACTS_TARBALL=./dist/{{.ProjectName}}_{{.Version}}_linux_arm64.tar.gz
    extra_files:
      - ./
  - goarch: arm
    goarm: "6"
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv6
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v6
      - --build-arg=USE_GORELEASER_ARTIFACTS=1
      - --build-arg=GORELEASER_ARTIFACTS_TARBALL=./dist/{{.ProjectName}}_{{.Version}}_linux_armv6.tar.gz
    extra_files:
      - ./
  - goarch: arm
    goarm: "7"
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv7
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
      - --build-arg=USE_GORELEASER_ARTIFACTS=1
      - --build-arg=GORELEASER_ARTIFACTS_TARBALL=./dist/{{.ProjectName}}_{{.Version}}_linux_armv7.tar.gz
    extra_files:
      - ./
  - goarch: ppc64le
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-ppc64le
    use: buildx
    build_flag_templates:
      - --platform=linux/ppc64le
      - --build-arg=USE_GORELEASER_ARTIFACTS=1
      - --build-arg=GORELEASER_ARTIFACTS_TARBALL=./dist/{{.ProjectName}}_{{.Version}}_linux_ppc64le.tar.gz
    extra_files:
      - ./
  - goarch: s390x
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-s390x
    use: buildx
    build_flag_templates:
      - --platform=linux/s390x
      - --build-arg=USE_GORELEASER_ARTIFACTS=1
      - --build-arg=GORELEASER_ARTIFACTS_TARBALL=./dist/{{.ProjectName}}_{{.Version}}_linux_s390x.tar.gz
    extra_files:
      - ./

docker_manifests:
  - name_template: ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-386
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-amd64
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-arm64
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv6
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv7
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-ppc64le
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-s390x
  - name_template: ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Major}}.{{.Minor}}
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-386
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-amd64
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-arm64
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv6
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv7
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-ppc64le
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-s390x
    skip_push: auto
  - name_template: ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Major}}
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-386
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-amd64
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-arm64
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv6
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv7
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-ppc64le
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-s390x
    skip_push: auto
  - name_template: ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:latest
    image_templates:
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-386
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-amd64
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-arm64
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv6
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-armv7
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-ppc64le
      - ghcr.io/{{envOrDefault "GITHUB_REPOSITORY" "goproxy/goproxy"}}:{{.Version}}-s390x
    skip_push: auto

snapshot:
  version_template: '{{trimprefix .Summary "v"}}'

release:
  prerelease: auto
