version: 2

env:
  - DOCKER_IMAGE_REPO={{envOrDefault "DOCKER_IMAGE_REPO" "goproxy"}}

before:
  hooks:
    - go mod download

builds:
  - id: goproxy
    main: ./cmd/goproxy
    binary: bin/goproxy
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/goproxy/goproxy/cmd/goproxy/internal.versionOverride=v{{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
      - linux_ppc64le
      - linux_riscv64
      - linux_s390x
      - windows_386
      - windows_amd64
      - windows_arm64
    mod_timestamp: "{{.CommitTimestamp}}"

dockers_v2:
  - id: goproxy
    dockerfile: Dockerfile
    images:
      - "{{.Env.DOCKER_IMAGE_REPO}}"
    tags:
      - "{{.Version}}"
      - "{{.Major}}.{{.Minor}}"
      - "{{.Major}}"
      - latest
    platforms:
      - linux/386
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
      - linux/ppc64le
      - linux/riscv64
      - linux/s390x
    build_args:
      USE_GORELEASER_ARTIFACTS: "1"

snapshot:
  version_template: '{{trimprefix .Summary "v"}}'

release:
  prerelease: auto
